### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by yeuem1vannam** [framgia/rails5_skeleton#1]
Theo tôi nghĩ tên repo nên  hướng mục tiêu hơn
- rails5-boileplate

**Comment by chikim** [comment]
@yeuem1vannam làm nào đổi repo name nhở :-ss
ko lẽ phải tạo lại

**Comment by yeuem1vannam** [comment]
@chikim Vào setting có phần `Rename` đó

**Comment by chikim** [comment]
@yeuem1vannam review pls
https://github.com/framgia/rails5_skeleton/pull/5
